// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5GtnX-NOrftri44OKUHxBqsvZ0Pat06s',
    appId: '1:297158684961:web:e943bf8e6333ec51118e60',
    messagingSenderId: '297158684961',
    projectId: 'flutter-todo-a',
    authDomain: 'flutter-todo-a.firebaseapp.com',
    storageBucket: 'flutter-todo-a.appspot.com',
    measurementId: 'G-39QDQQC3SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRn3Lxqy_rYe6KrtJpcHsd011mHYKXhTw',
    appId: '1:297158684961:android:1da2fbc1977b416b118e60',
    messagingSenderId: '297158684961',
    projectId: 'flutter-todo-a',
    storageBucket: 'flutter-todo-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO7sysBhw_DghLSqe7ORPtRdoHkf11Lk0',
    appId: '1:297158684961:ios:f702500f9a91cb52118e60',
    messagingSenderId: '297158684961',
    projectId: 'flutter-todo-a',
    storageBucket: 'flutter-todo-a.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO7sysBhw_DghLSqe7ORPtRdoHkf11Lk0',
    appId: '1:297158684961:ios:f702500f9a91cb52118e60',
    messagingSenderId: '297158684961',
    projectId: 'flutter-todo-a',
    storageBucket: 'flutter-todo-a.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5GtnX-NOrftri44OKUHxBqsvZ0Pat06s',
    appId: '1:297158684961:web:c947878e638e7f3f118e60',
    messagingSenderId: '297158684961',
    projectId: 'flutter-todo-a',
    authDomain: 'flutter-todo-a.firebaseapp.com',
    storageBucket: 'flutter-todo-a.appspot.com',
    measurementId: 'G-TBFTDQK205',
  );
}
